import type { Metadata } from "next"
import { Geist_Mono, Inter } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import { cn } from "@/lib/utils"
import { TooltipProvider } from "@/components/ui/tooltip"

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const meem = localFont({
  src: [
    {
      path: "../public/fonts/Meem-UltraLight.woff2",
      weight: "50",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-DemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Meem-UltraBold.woff2",
      weight: "950",
      style: "normal",
    },
  ],
  variable: "--font-meem",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, geistMono.variable, meem.variable)}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          {children}
        </TooltipProvider>
      </body>
    </html>
  )
}
